config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  
  root to: 'posts#index'

  resources :posts do #creates set of routes index, show, new/create, edit/update, destroy
    collection { post :import }
  end 

resources :hnhh
  get 'hnhh/show'

  get 'home/index'
  get 'home/trapmusic'

  get 'search/index'
  get 'search/mixtapes'
  get 'search/main'
  get 'search/news'
  get 'search/audiomack'
  get 'search/hiphopearly'
  get 'search/hotnewhiphop'
  get 'search/audiocastle'
  get 'search/videos'
  get 'search/howflyhiphop'
  get 'search/worldstar'
  get 'search/reddit'
  
  %w(index trapmusic mixtapes main news audiomack hiphopearly hotnewhiphop audiocastle videos howflyhiphop worldstar reddit).each do |page|
  match "#{page}", to: "search/#{page}", via: 'get'
end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

   def requires 
    require 'mechanize'
    require 'nokogiri'
    require 'open-uri'
  end 


  def index  
    @News = News.all

    @mixtape = Mixtapes.all
  

  end   

  def news 

    @News = News.all
    
  	requires

    agent = Mechanize.new
    page = agent.get('http://www.hotnewhiphop.com/articles/news/')
    @news_links = page.search('.title-10 a')
    @news_links.shift
    @images = page.search('.mr10 img')

    #zip and map the arrays to display

    @pit = Hash[@news_links.zip(@images)]


    @pit.each do |x, i|
          artical_name_title = i.attr('alt').to_s
          news_link = x.attr('href').to_s
          image_link =  i.attr('src').to_s

          if News.exists?(:title => artical_name_title)
            next
          else 
            News.create(:title => artical_name_title, :image => image_link, :link => news_link)
          end 
        end 







  end 

  def hotnewhiphop
    requires

    agent2 = Mechanize.new 


    page2 = agent2.get('http://www.hotnewhiphop.com/archive/')


    @hnhh_songs = page2.search('.songChart img')
    
        #@hnhh_songs.attr('href')
    
        @hnhh_links = page2.search('.songChart-cover-anchor')
    
        @hnhh_hash = @hnhh_links.zip(@hnhh_songs)

        @hnhh_hash.each do |x, i|
          hnhh_link = "http://www.hotnewhiphop.com" + x.attr('href').to_s
          image_link = i.attr('src').to_s
          artist_name_title = x.attr('title').to_s

        end 

    
  end 

  def audiomack
    requires

    agent = Mechanize.new
    page = agent.get('http://www.audiomack.com/songs/day') 
    #scrapes all other data from audiomack top 10 songs/day
        @post_links = page.search('.player_image')

        #scrapes the images from audiomack top 10
        @audiomack_images = page.search('.player_image img')
 
        #the line below was experimentation. It zips the images array into the postlinks array. Might want to look into the .flatten mathod later
        #@new_array = @audiomack_images.zip(@post_links)

        #jam is the cominded array of postlinks and audiomack images
        @jam = @audiomack_images.zip(@post_links)




=begin
    page13 = agent.get('http://www.audiomack.com/trending')
    @trending_links = page13.search('.artist-title a')
    @trending_images = page13.search('.cover img')
    @trending_hash = Hash[@trending_links.zip(@trending_images)]
=end
=begin
    #Take our search array, insert it into a query
    search_terms.each do |search|
    page = agent.get("http://www.asus.com/Search/?SearchKey=#{search}")
    links =  page.links.find_all{ |l| l.text =~ /#{search}/i}
    links.each { |links_text| results_file.write( "#{links_text}\n" ) }
    end 

    var = page.search('.artist-title')
    page15 = agent.get('http://www.google.com')
    google = page15.form
    search_term = var[0].text
    google.field_with(:name => "q").value = search_term
    @search_results = agent.submit(google)
=end 
    
  end



  def hiphopearly
    requires

    agent4 = Mechanize.new 
    page4 = agent4.get('http://www.hiphopearly.com/')
    @hiphopearly = page4.search('.text')
    @hiphopearly.attr('href')

    @hhe_images = page4.search('#left-column .thumb')

    @hhehash = Hash[@hiphopearly.zip(@hhe_images)]


    
  end 

  def audiocastle
    requires

    agent3 = Mechanize.new 
    page3 = agent3.get('http://www.audiocastle.net/tracks/browse')
    @audiocastle = page3.search('a .lighten_content li, a')
    @audiocastle.attr('href')

    
  end 

  def mixtapes 
    requires 

    @mixtape = Mixtapes.all

    agent7 = Mechanize.new 
    page7 = agent7.get('http://www.livemixtapes.com/main.php')
    @lm_links = page7.search('#content span a')
    @lm_images = page7.search('.mixtape_cover img')
    @lm_hash = Hash[@lm_links.zip(@lm_images)]

    @lm_hash.each do |x, i|
          artist_name_title = x.text
          image_link =  i.attr('src').to_s 
          livemixtapes_link = "http://www.livemixtapes.com" + x.attr('href').to_s 

          if Mixtapes.exists?(:artist => artist_name_title)
            next
          else 
            Mixtapes.create(:artist => artist_name_title, :mx_cover => image_link, :mx_name => livemixtapes_link)
          end 
        end 




    agent8 = Mechanize.new
    page8 = agent8.get('http://www.datpiff.com/')
    @dp_links = page8.search('#leftColumnWide .title a')
    @dp_images = page8.search('#leftColumnWide .contentThumb img')
    @dp_artist = page8.search('.artist')
    @dp_hash = Hash[@dp_links.zip(@dp_images)]

    @new_array = @dp_links.zip(@dp_images, @dp_artist)

    @new_array.each do |x, i, z| 
      dp_link = "http://www.datpiff.com" + x.attr('href')
      dp_image = i.attr('src') 
      dp_artist = x.attr('title').to_s.gsub(/^(listen to )/, '') 
      dp_mxname = z.text 

      if Mixtapes.exists?(:artist => dp_artist)
          next
        else 
          Mixtapes.create(:artist => dp_artist, :mx_cover => dp_image, :mx_name => dp_mxname, :mx_artist =>dp_link )
        end 
    end


  end 


 

  def videos
      requires  

      agent5 = Mechanize.new 
      page5 = agent5.get('http://www.hiphopdx.com/index/videos/p.1')
      @videos_hhdx = page5.search('h3 a')

      @hhdx_images = page5.search('#wirelist2 img')

      @hhdx_hash = Hash[@videos_hhdx.zip(@hhdx_images)]

      agent6 = Mechanize.new 
      page6 = agent6.get('http://www.hotnewhiphop.com/videos/ ')
      @hnhh_video_links = page6.search('.list-item-title a')
      @hnhh_video_images = page6.search('.video-thumb .w100per')
      @hnhh_video_hash = Hash[@hnhh_video_links.zip(@hnhh_video_images)]



  end 

  def worldstar
  end 

  def howflyhiphop
    requires

      agent9 = Mechanize.new 
      page9 = agent9.get('http://www.howflyhiphop.com/category/singles/')
      @hfhh_links = page9.search('.entry-title a')
      @hfhh_images = page9.search('.size-full')
      @hfhh_hash = Hash[@hfhh_links.zip(@hfhh_images)]

      page10 = agent9.get('http://www.howflyhiphop.com/category/singles/page/2/')
      @hfhh_p2_links = page10.search('.entry-title a')
      @hfhh_p2_images = page10.search('.size-full')
      @hfhh_hash2 = Hash[@hfhh_p2_links.zip(@hfhh_p2_images)]

  end 


  def reddit
    requires

    agent11 = Mechanize.new
    page11 = agent11.get('http://www.reddit.com/r/trapmuzik/')
    @tm_links = page11.search('.title .may-blank')
    # @tm_links_native = page11.search('.self .title') <-- fix native reddit links later 
    @tm_images = page11.search('#siteTable .thumbnail img')

    @tm_hash = Hash[@tm_images.zip(@tm_links)]

    @tm = page11.search('.thumbnail may-blank img')




  end 


  
 
end 

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/audiocastle.html.erb
<div id="siteContainer">
	<div class="alltheInfo">
		

		<p>find away to get images on this page</p><br />
		<p><%= link_to "AudioCastle", 'http://www.audiocastle.net/' %> links.</p><br />


		
			<% @audiocastle[34..53].each do |f| %>
			<%= f.text.to_s %><br />
			<%= link_to "AudioCastle Link", f.attr('href').to_s %><br />
			<br />
			<% end %>


		
	</div>
</div>

app/views/search/audiomack.html.erb
<div id="siteContainer">
	<div class="alltheInfo">


		<h2>These are the <%= link_to "AudioMack", 'http://www.audiomack.com/' %> links for today</h2><br />
		
		<!--
		Make it link to a loud hip hop page that will scrape the download links from the top results. 
		-->
	<% @jam.each do |x, i| %>
	<div class="square3">
	<a href="http://www.audiomack.com<%= i.attr('data-url').to_s %>"><img src="<%= x.attr('src').to_s %>"/></a><br />
	<%= i.attr('data-artist').to_s %><br />
	<%= i.attr('data-title').to_s %><br />
	<% link = 'http://www.google.com/search?q=' + i.attr('data-artist').to_s.delete("&").gsub(/\s+/, "+") + i.attr('data-title').to_s.delete("&").gsub(/\s+/, "+") +'+download' %>
		<a href=<%= link %> target="_blank">Download</a>
	<% link1 = 'https://www.youtube.com/results?search_query=' + i.attr('data-artist').to_s.delete("&").gsub(/\s+/, "+") + i.attr('data-title').to_s.delete("&").gsub(/\s+/, "+") %><br />
		<a href=<%= link1 %> target="_blank">Youtube</a><br />
	</div>
	<% end %>
			


	</div>
</div>

app/views/search/hiphopearly.html.erb
<div id="siteContainer">
	<div class="alltheInfo">




	<p><%= link_to "HipHopEarly", 'http://www.hiphopearly.com/' %> links </p>

	<br />
	<br />
	<br />



	<% @hhehash.each do |x, i| %>
	<div class="square">
	<a href="http://www.hiphopearly.com<%= x.attr('href').to_s %>"><img src="http://www.hiphopearly.com<%= i.attr('src').to_s %>"/></a><br />
	<%= x.text %><br />
	</div>
	<% end %>


		

		
	</div>
</div>

app/views/search/hotnewhiphop.html.erb
<div id="siteContainer">
	<div class="alltheInfo">

		<p>These are the <%= link_to "HotNewHipHop", 'http://www.hotnewhiphop.com/' %> links for this week hnnh/archive</p><br />
		<p>This page needs low quality pics fixed later</p><br />
		
		<br />
		<br />

		<% @hnhh_hash.each do |x, i| %>
		<div class="square">
		<a href="<%= "http://www.hotnewhiphop.com" + x.attr('href').to_s %>"><img src="<%= i.attr('src').to_s %>" style=""/></a><br />
		<%= x.attr('title').to_s %><br />
		<% link = 'http://www.google.com/search?q=' + x.attr('title').to_s.delete("&").gsub(/\s+/, "+") +'+download' %>
		<a href=<%= link %> target="_blank">Download</a>
	<% link1 = 'https://www.youtube.com/results?search_query=' + i.attr('title').to_s.delete("&").gsub(/\s+/, "+") %><br />
		<a href=<%= link1 %> target="_blank">Youtube</a><br />
		</div>
		<% end %>
		
	</div>
</div>

app/views/search/howflyhiphop.html.erb
<div id="siteContainer">
	<div class="alltheInfo">

		<p>These are the <%= link_to "HowFlyHipHop", 'http://www.howflyhiphop.com/category/singles/' %> links for today</p><br />
		<!--
		<p>remeber to add download buttons later.</p><br />
		<p>Think about scraping the other pages also.</p><br />
		-->

	<% @hfhh_hash.each do |x, i| %>
	<div class="square3">
	<a href="<%= x.attr('href') %>"><img src="<%= i.attr('src') %>" style="width: 275px; height: 275px"/></a><br />
	<%= x.text %><br />
	</div>
	<% end %>

	<% @hfhh_hash2.each do |x, i| %>
	<div class="square3">
	<a href="<%= x.attr('href') %>"><img src="<%= i.attr('src') %>" style="width: 275px; height: 275px"/></a><br />
	<%= x.text %><br />
	</div>
	<% end %>
			


	</div>
</div>

app/views/search/index.html.erb
<!-- 
<p>add atrilli to the list multiple pages</p>
<p>page of realease dates http://cantstophiphop.com/release-dates/ maybe find a comprable list</p>
-->



<div id="siteContainer">
	<div class="alltheInfo">
	<p>Links to popular hiphop site and some links and news/mixtapes/singles from each</p><br />


		<a href="/search/audiomack"><img src="http://i.imgur.com/nj3QqLr.jpg"/></a>
		<a href="/search/hotnewhiphop"><img src="http://i.imgur.com/wK3Gkub.jpg"/></a>
		<a href="/search/videos"><img src="http://i.imgur.com/c5daQLK.jpg"/></a>

		<br />
		<br />


		<a href="/search/audiocastle"><img src="http://i.imgur.com/5OL32Ff.jpg"/></a>
		<a href="/search/hiphopearly"><img src="http://i.imgur.com/mBU8hkw.jpg"/></a>
		<%= link_to(image_tag("http://i.imgur.com/RF3HOUC.jpg"), search_mixtapes_path) %>
		<a href="/search/howflyhiphop"><img src="http://i.imgur.com/5n53gLF.jpg"/></a>
		<a href="/search/worldstar"><img src="http://i.imgur.com/AuYMRm8.jpg"/></a>
		<a href="/search/reddit"><img src="http://i.imgur.com/ikmHJyB.jpg"/></a>
		
		



</div>
</div>

app/views/search/main.html.erb
<br />
<br />
<br />
<%= link_to "Home", posts_path %><br/>



<br />
<br />
<br />

underground clothing - this page will eventually be the store 



<br />
<br />
<br />


<%= link_to "L.I.E", 'http://www.loveisearth.com/' %><br />
<%= link_to "Silent Antics Clothing", 'http://www.silentanticsclothing.com/' %> <br />

http://blkmkt.us/ <br />
http://rsvpgallery.com/ <br />
http://thehighsociety.com/

app/views/search/mixtapes.html.erb
mixtapes.html.erb

<div id="siteContainer">
	<div class="alltheInfo">
						
<p>add most views for last 30 days page off livemixtapes.</p>
<p>Albums dont have artist names on datpiff links</p>
<p> make sure to incorporate the "best song on this mixtape feature </p>"
-->

<% @new_array.each do |x, i, z| %>
<div class="square3">
	<a href="http://www.datpiff.com<%= x.attr('href') %>"><img src="<%= i.attr('src') %>"/></a><br />
	<%= x.attr('title').to_s.gsub(/^(listen to )/, '') %><br />
	<%= z.text %><br />
</div>
<% end %>

<h1>MIXTAPES PAGE</h1>
<p><a href="index">Home</a></p>
<br />
<br />

<%= link_to "Datpiff", 'http://www.datpiff.com/' %><br />
<%= link_to "LiveMixtapes", 'http://www.livemixtapes.com/main.php' %><br />

<br />
<br />



<br />
<br />

<% @lm_hash.each do |x, i| %>
<div class="square3">
<a href="http://www.livemixtapes.com<%= x.attr('href') %>"><img src="<%= i.attr('src') %>"/></a><br />
<%= x.text %><br />
</div>
<% end %>

<br />
<br />
<br />
<br />

<br />
<br />
<br />
<br />

<br />

			


</div>
</div>

app/views/search/news.html.erb
<div id="siteContainer">
	<div class="alltheInfo" >
		
		<p>This is the AUDIOMACK NEWS for today - still need to fix link code ADD http://www.complex.com/music/</p>
		<br />
			<br />
			<br />
			<br />

		<% @pit.each do |k, v| %>
			<div class="square">
				<a href="<%= k.attr('href').to_s %>"><img src="<%= v.attr('src').to_s %>"/></a>
					<div class="inside-square">
						<p><%= v.attr('alt').to_s %></p>
					</div>
			</div>
		<% end %>

	
			<br />
			<br />
 			<br />

 			<% @News.each do |x| %>
 				<%= x.title %><br />
 			<% end %>




 			
	</div> 			
</div>

app/views/search/reddit.html.erb
<div id="siteContainer">
	<div class="alltheInfo">


<p>reddit general hiphop news and links</p>
<p>Currently streaming from http://www.reddit.com/r/trapmuzik/ - Links dont match images </p>
<p>http://www.reddit.com/r/hiphopheads/ COMING SOON </p><br />



<br />



<% @tm_hash.each do |x, i| %>
<div class="square">
<a href="<%= i.attr('href').to_s %>"><img src="http://<%= x.attr('src')[2..100] %>"/></a><br />

	<%= i.attr('href') %><br />
	<%= i.text %><br />
</div>
<% end %>


<br />
<br />
<br />
<br />


</div>
</div>

app/views/search/videos.html.erb
<div id="siteContainer">
	<div class="alltheInfo">

	<p>add http://www.trillhd.com/browse </p>

		

		<% @hhdx_hash.each do |x, i| %>
		<div class="square3">
		<a href="http://www.hiphopdx.com<%= x.attr('href').to_s %>"><img src="<%= i.attr('src').to_s %>"/></a><br />
		<%= x.text %><br />
		</div>
		<% end %>

		<br />
		<br />
		<br />
		<br />

		<div style="margin-top:2100px">
		<% @hnhh_video_hash.each do |x, i| %>
		<div class="square">
		<a href="<%= x.attr('href') %>"><img src="<%= i.attr('src') %>"/></a><br />
		<%= x.text %><br />
		</div>		
		<% end %>
		</div>

</div>
</div>

app/views/search/worldstar.html.erb
<div id="siteContainer">
	<div class="alltheInfo">

<p><%= link_to "WorldStar", 'http://www.worldstarhiphop.com/videos/' %> LINKS COMING SOON! </p>

</div>
</div>