config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  
  root to: 'posts#index'

  resources :posts do #creates set of routes index, show, new/create, edit/update, destroy
    collection { post :import }
  end 

resources :hnhh
  get 'hnhh/show'

  get 'home/index'
  get 'home/trapmusic'

  get 'search/index'
  get 'search/mixtapes'
  get 'search/main'
  get 'search/news'
  get 'search/audiomack'
  get 'search/hiphopearly'
  get 'search/hotnewhiphop'
  get 'search/audiocastle'
  get 'search/videos'
  get 'search/howflyhiphop'
  get 'search/worldstar'
  get 'search/reddit'
  
  %w(index trapmusic mixtapes main news audiomack hiphopearly hotnewhiphop audiocastle videos howflyhiphop worldstar reddit).each do |page|
  match "#{page}", to: "search/#{page}", via: 'get'
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="description" content="Loudhiphop aggregates all the new music from your favorite hiphop related websites and easily displays the youtube video and download links for each song." >
  <title>Loudhiphop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="https://www.google.com/jsapi" type="text/javascript"></script>
  <script src="https://www.youtube.com/iframe_api"></script>
  <%= csrf_meta_tags %>


  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <script>
  $(function() {
    $( "#tabs1, #tabs2" ).tabs();
  });
  </script>

<!-- google script -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56853650-1', 'auto');
  ga('send', 'pageview');

  </script>
<!-- end of google script -->
  
</head>
<body>



<header id="header" class="fixed-header">

			<div class="container full-width-container">

				<div class="brand-logo"><a href="http://www.loudhiphop.com">LOUDHIPHOP</div>


				<nav class="main-nav">

					<ul>
						
                        <li><a href="/">Top Songs</a></li>

						            <li><%= link_to "Top Mixtapes/Albums", home_trapmusic_path %></li>

                        <li><%= link_to "My Playlist", home_index_path %></li>

                        <li><%= link_to "Shop", search_main_path %></li>
                        
                        <!-- add dropdown here -->
                        <li><%= link_to "Search", search_index_path %></li>
					</ul>

				</nav><!--/.main-nav-->


                <form id="site-search" class="search-form" action="/search" method="get">

                    <input type="text" class="search" value="" placeholder="Search for artists, songs, albums!" name="q" />

                </form><!--/#site-search-->
	

			</div><!--/.full-width-container-->

</header>

<% flash.each do |key, value| %>
	<p><%= value %></p>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>